name: mobile
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dio: ^5.4.3+1
  shared_preferences: ^2.2.3
  infinite_scroll_pagination: ^4.0.0
  carousel_slider: ^4.2.1
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/document.jpeg"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/document.jpeg"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/document.jpeg"
    icon_size: 48
  macos:
    generate: true

flutter:
  uses-material-design: true
  assets:
    - assets/document.jpeg
